### PR TITLE
Update LICENSE to the new naming guidelines

### PR DESCRIPTION
**Pull request by brunoocasali**
I created an automated PR for all the integration repositories, but this one I couldn't because it does not have a particular label `skip-changelog`.

### CODE REVIEW

**Comment by brunoocasali** [comment]
> Does this apply to any Meilisearch-owned repo?

Yes! And we will need to change it every year! But we have an automated script to help us doing that, so no problem :)

**Comment by ferdi05** [comment]
Was it done already?

**Comment by brunoocasali** [comment]
Yes! all the integration repositories, received a PR like this: https://github.com/meilisearch/meilisearch-php/pull/311, https://github.com/meilisearch/meilisearch-ruby/pull/309, https://github.com/meilisearch/meilisearch-swift/pull/279 (we took care of maintaining the previous copyrights as well)

**Comment by ferdi05** [comment]
ok then there are some other repos that may need this

- [Demos](https://github.com/meilisearch/demos)
- [Tutorials](https://github.com/meilisearch/tutorials/blob/main/LICENSE)

Should we add the lable `skip-changelog` (I have no idea what it is used for)

**Comment by brunoocasali** [comment]
Well, for some reason our script didn't work for both repositories you send me 🤔 
Is there anything special about them?

**Comment by curquiza** [comment]
> Should we add the lable skip-changelog (I have no idea what it is used for)

it's only if you use the release drafter, I mean, automation to create release on GitHub in an easier way, which is not your case

**Comment by brunoocasali** [comment]
Ok, good to know @curquiza. I thought since the `meili-bot` contributes to a public repo, write access should not be required. But now make sense because `meili-bot` does that directly to the repo (it does not fork it).

**Comment by curquiza** [comment]
Indeed, it does not fork and no one in GitHub can create a new branch directly to the repo (without forking) without the write access :)

**Pull request merged**
