### PR TITLE
Move all MeiliSearch references to the new brand

### PR DESCRIPTION
**Pull request by brunoocasali**
Just replace all `MeiliSearch` by `Meilisearch` 😄

### CODE REVIEW

**Comment by sanders41** [comment]
@brunoocasali there is also one in CONTRIBUTING.md. Saw it yesterday and meant to do a PR but forgot.

**Comment by brunoocasali** [comment]
> @brunoocasali there is also one in CONTRIBUTING.md. Saw it yesterday and meant to do a PR but forgot. The license also needs the name updated.

Good catch @sanders41! I tried to avoid cloning the repo 😅, but Github cannot handle multiple changes online (or I just don't know how) :/

**Comment by sanders41** [comment]
I had the same issue, that's why I forgot to come back and do the PR :smile:

**Comment by ferdi05** [comment]
Absolutely forgot about it. Thanks so much @brunoocasali @sanders41 :)

**Pull request merged**
