### PR TITLE
Add cool SVG logo with glasses

### PR DESCRIPTION
**Pull request by kissu**
## Related issue
Nothing broken here, we were mainly missing a nice SVG like everybody does IMO because we also want to be _awesome_. ✨ 

## What does this PR do?
- adds `.gitignore` to prevent files from MacOS to be committed
- adds a dope logo like the [cools kids](https://github.com/vitejs/awesome-vite)

### CODE REVIEW

**Comment by ferdi05** [comment]
Hi @kissu thanks for your contribution.
I don't really get why a `.gitignore` file is needed here, the repo is mainly a README Markdown file.

I'd suggest you to remove it, I'm only looking for PRs editing the Readme file

**Review by ferdi05 — CHANGES_REQUESTED** [review]
Hi @kissu thanks for your contribution.
I don't really get why a .gitignore file is needed here, the repo is mainly a README Markdown file.

Before we move on, can you remove it, we're only looking for PRs editing the Readme file.

**Comment by ferdi05** [comment]
Thanks @kissu well the only file I want to manage is the readme file (and possibly some graphic files), so I'd rather get rid of the `.gitignore` file, it's not really needed here.

**Comment by kissu** [comment]
Alright, I removed the `.gitignore` entirely. ✅

**Review by chayaline — CHANGES_REQUESTED** [review]
Hello @kissu, 
Thanks for this PR, it would indeed be great to have a logo on this repo!

I am a Product designer at Meilisearch and I have some feedback for you, in order to make it 🙌🏻 perfect.

- the font you chose doesn't fit well with Meilisearch's style, could you instead use Poppins? you can download it for free on [google fonts](https://fonts.google.com/specimen/Poppins) or activate it on [Adobe fonts](https://fonts.adobe.com/fonts/poppins#fonts-section) if you used Adobe products to design it.

- can you center the text visually with the logomark, instead of by pixels?
Due to our logomark being slanted it looks unbalanced if we perfectly center the text. As you can see on this image, if you slightly offcenter the logomark it looks better.
Capture d’écran 2022-10-17 à 11 18 53

- the sunglasses are a cool idea 👍🏻 the only issue with them is that the teal doesn't go well over the hot pink because they have the same contrast value. Plus for some type of colorblindness it makes it difficult to distinguish:
Capture d’écran 2022-10-17 à 11 21 25 
Can you tweak the color a little bit or find a way to make it work better? Here is our color palette to help you:

meilisearch-colors

Thanks again for your contribution, and don't hesitate to ping me if you need anything 🙂

**Comment by ferdi05** [comment]
Thanks so much @chayaline for this comprehensive review :)

**Comment by ferdi05** [comment]
No one seems to have resumed this work, so closing it

**Pull request closed without merging**
